# Markup Settings, removed [markup] root key per hugo docs

defaultMarkdownHandler = 'goldmark'

[asciidocExt]
  backend = 'html5'
  extensions = []
  failureLevel = 'fatal'
  noHeaderOrFooter = true
  preserveTOC = false
  safeMode = 'unsafe'
  sectionNumbers = false
  trace = false
  verbose = false
  workingFolderCurrent = false
  [asciidocExt.attributes]
[blackFriday]
  angledQuotes = false
  footnoteAnchorPrefix = ''
  footnoteReturnLinkContents = ''
  fractions = true
  hrefTargetBlank = true
  latexDashes = true
  nofollowLinks = true
  noreferrerLinks = true
  plainIDAnchors = true
  skipHTML = false
  smartDashes = true
  smartypants = true
  smartypantsQuotesNBSP = false
  taskLists = true
[goldmark]
  [goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"
    [goldmark.parser.attribute]
      block = true
      title = true
  [goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false
[highlight]
  anchorLineNos = true
  codeFences = true
  guessSyntax = true
  hl_Lines = ""
  hl_inline = false
  lineAnchors = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = false
  noHl = false
  #style = "codepen"
  style = 'monokai'
  tabWidth = 2
[tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 2
