# Mediatype Settings, removed [mediaTypes] root key per hugo docs
## https://gohugo.io/templates/output-formats/#media-types

['application/json']
  suffixes = ['json']
['application/manifest+json']
  suffixes = ['webmanifest']
['application/octet-stream']
  suffixes = ['webmanifest']
['application/pdf']
  suffixes = ['pdf']
['application/rss+xml']
  suffixes = ['xml', 'rss']
['application/toml']
  suffixes = ['toml']
['application/wasm']
  suffixes = ['wasm']
['application/xml']
  suffixes = ['xml']
['application/yaml']
  suffixes = ['yaml']
['font/otf']
  suffixes = ['otf']
['font/ttf']
  suffixes = ['ttf']
['image/bmp']
  suffixes = ['bpm']
['image/gif']
  suffixes = ['gif']
['image/jpeg']
  suffixes = ['jpg', 'jpeg', 'jpe', 'jif', 'jfif']
['image/png']
  suffixes = ['png']
['image/svg+xml']
  suffixes = ['svg']
['image/tiff']
  suffixes = ['tif', 'tiff']
['image/webp']
  suffixes = ['webp']
['text/calendar']
  suffixes = ['ics']
['text/css']
  suffixes = ['css']
['text/csv']
  suffixes = ['csv']
['text/enriched']
  suffixes = ['enr']
['text/html']
  suffixes = ['asp', 'htm', 'html']
['text/javascript']
  suffixes = ['js', 'jsm', 'mjs']
['text/jsx']
  suffixes = ['jsx']
['text/markdown']
  suffixes = ['md', 'markdown']
['text/plain']
  suffixes = ['txt']
['text/tsx']
  suffixes = ['tsx']
['text/typescript']
  suffixes = ['ts']
['text/x-sass']
  suffixes = ['sass']
['text/x-scss']
  suffixes = ['scss']
['video/3gpp']
  suffixes = ['3gpp', '3gp']
['video/mp4']
  suffixes = ['mp4']
['video/mpeg']
  suffixes = ['mpg', 'mpeg']
['video/ogg']
  suffixes = ['ogv']
['video/webm']
  suffixes = ['webm']
['video/x-msvideo']
  suffixes = ['avi']

