# root key [params] removed per hugo docs

# Main Settings
defaultSkin = "light"  # select default UI: "light" or "dark"
dateFormat = "September 20, 2023"
authorName = "Kaska Miskolczi"
disqusComments = "awestomates" #YOUR DISQUS COMMENTS SHORTNAME
formspreeURL = "" #YOUR FORMSPREE URL
googleAnalytics = "" #YOUR GOOGLE ANALYTICS CODE

# Preloader Settings
[preloader]
  logo = "images/logo.svg"
  alt = "Awestomates"

# Header Settings
[header]
  logo = "images/logo.svg"
  logo_alt =  "Awestomates"

# Footer Settings
[footer]
  copyright = "© 2023 <strong>Awestomates</strong>. All rights reserved"
  developer = "Developed with <i class='fa fa-heartbeat'></i> by <strong><a target='_blank' href='https://linkedin.com/in/rosenfaden'>Kaska</a></strong>"

# Social Settings
[[social]]
  title = "Twitter"
  icon = "fab fa-twitter"
  url = "https://www.twitter.com/"
  weight = 1
[[social]]
  title = "Dribbble"
  icon = "fab fa-dribbble"
  url = "https://www.dribbble.com/"
  weight = 2
[[social]]
  title = "Behance"
  icon = "fab fa-behance"
  url = "https://www.behance.net/"
  weight = 3

# Sidebar
[sidebar]
  enable = 1 #SIDEBAR SHOW: [ 1 - yes, 0 - no ]
  search = 1 #SIDEBAR SEARCH WIDGET: [ 1 - yes, 0 - no ]
  latestPosts = 1 #SIDEBAR LATEST POSTS WIDGET: [ 1 - yes, 0 - no ]
  categories = 1 #SIDEBAR CATEGORIES TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
  tags = 1 #SIDEBAR TAG TAXONOMY WIDGET: [ 1 - yes, 0 - no ]
