# root key [sitemap] removed per hugo docs
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

## changefreq: Valid values are always, hourly, daily, weekly, monthly, yearly, and never. Default is "" (change frequency omitted from rendered sitemap).