name = "awestomates"
license = "GPL"
licenselink = "https://awestomates.netlify.app/license"
description = "Awestomates - An Awesome place for New Ostomates of all kinds!"
homepage = "https://awestomates.netlify.app"
tags = ["awestomates", "ostomy", "ostomates", "urostomy", "illiostomy", "colostomy", "cancer", "bladder", "urology", "gasteroenterology", "gastro", "colon", "journey"]
features = ['bootstrap 4', 'responsive design', 'blog', 'responsive', 'minimal', 'resume', 'cv', 'hugo-theme', 'portfolio', 'creative', 'contact-form']
min_version = "0.41"

[author]
  name = "Kaska Miskolczi"
  homepage = "https://awestomates.netlify.app"
